### ISSUE TITLE
Tests? 

### ISSUE THREAD

**Issue by rwjblue** [webark/broccoli-file-manifest#1]
Would be really helpful to see/understand what is going on here if there were some tests.

I would suggest using [broccoli-test-helper](https://github.com/krisselden/broccoli-test-helper), which would let you do something like (pseudo code):

```js
it("should build", async function() {
    input.write({
      "src": {
        "ui": {
          "components": {
            "todo-item": {
              "style.scss": '/* todo item styles */'
            },
            "other-thing": {
              "style.scss": '/* other thing styles */'
            }
          }
        }
      }
    });

    await output.build();

    expect(output.read()).to.deep.equal({
      "src": {
        "ui": {
          "styles": {
            "app.scss": stripIndent`
              @import "src/ui/components/todo-item/style";
              @import "src/ui/components/other-thing/style";`
          },
          "components": {
            "todo-item": {
              "style.scss": '/* todo item styles */'
            },
            "other-thing": {
              "style.scss": '/* other thing styles */'
            }
          }
        }
      }
    });
});
```

**Comment by webark** [comment]
@rwjblue totally. I'll prioritize getting these in. A base readme would probably be nice as well.. 😵

**Comment by rwjblue** [comment]
Hehe, indeed.  FWIW, this is _exactly_ the kind of thing that I was thinking would be a great first step for the colocated styles movement 😄.

**Comment by webark** [comment]
@rwjblue added a few tests to show whats going on. Also setup travis.. but maybe with a new repo it take a bit to get started. (never have set one up before).

And glad we where on kind of the same page! Let me know what you think, and if there are any changes you might have made.. For one, I'm only outputting just the "manifest" files rather then them inside of the tree.. I then generally merge them back into the tree I passed.

**Comment by webark** [comment]
and @rwjblue I don't know if you saw, but i added a PR for colocated styles in the glimmer app pipeline.. https://github.com/glimmerjs/glimmer-application-pipeline/pull/67

Also, looks like travis worked, so closing this.
